insert into PROMO_REDEMPTION_REWARD
(PROMO_REDEMPTION_ID, PRODUCT_ID, UNIT, QUANTITY)
select a.ID, c.PRODUCT_ID, c.UNIT, PRIZE_QUANTITY
from PROMO_REDEMPTION a
join PROMO b
  on b.ID = a.PROMO_ID
join PROMO_TYPE_1_RULE c
  on c.PROMO_ID = b.ID
where b.PROMO_TYPE_ID = 1
and a.POST_IND = 'Y';

alter table PROMO_REDEMPTION drop column PRIZE_QUANTITY;