alter table STOCK_QTY_CONVERSION_ITEM add CONVERTED_QTY integer(5) null;

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CSE / UNIT_CONV_TIE from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CSE' and TO_UNIT = 'TIE';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CSE / UNIT_CONV_CTN from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CSE' and TO_UNIT = 'CTN';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CSE / UNIT_CONV_DOZ from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CSE' and TO_UNIT = 'DOZ';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CSE / UNIT_CONV_PCS from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CSE' and TO_UNIT = 'PCS';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_TIE / UNIT_CONV_CTN from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'TIE' and TO_UNIT = 'CTN';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_TIE / UNIT_CONV_DOZ from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'TIE' and TO_UNIT = 'DOZ';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_TIE / UNIT_CONV_PCS from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'TIE' and TO_UNIT = 'PCS';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CTN / UNIT_CONV_DOZ from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CTN' and TO_UNIT = 'DOZ';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_CTN / UNIT_CONV_PCS from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'CTN' and TO_UNIT = 'PCS';

update STOCK_QTY_CONVERSION_ITEM
set CONVERTED_QTY = QUANTITY * (select UNIT_CONV_DOZ / UNIT_CONV_PCS from PRODUCT where ID = STOCK_QTY_CONVERSION_ITEM.PRODUCT_ID)
where (select POST_IND from STOCK_QTY_CONVERSION where ID = STOCK_QTY_CONVERSION_ID) = 'Y'
and CONVERTED_QTY is null
and FROM_UNIT = 'DOZ' and TO_UNIT = 'PCS';

alter table PAYMENT add CREATE_DT date null;
update PAYMENT set CREATE_DT = curdate();
alter table PAYMENT change CREATE_DT CREATE_DT date not null;
