insert into USER (ID, USERNAME) values (1, 'PJ');

insert into MANUFACTURER (NAME) values ('PEDIAHEALTH CORPORATION');
insert into MANUFACTURER (NAME) values ('PHARMA EAST MEDICAL CORP.');
insert into MANUFACTURER (NAME) values ('QUANTUM RUBBER PRODUCTS CORP.');
insert into MANUFACTURER (NAME) values ('NUTRAHERB INC.');
insert into MANUFACTURER (NAME) values ('ALKAPURE WATER RESOURCES INC.');
insert into MANUFACTURER (NAME) values ('CROFS CONSTRUCTION AND DEVELOPMENT CO.');
insert into MANUFACTURER (NAME) values ('FIL-SCAN EXPORTS, INC.');
insert into MANUFACTURER (NAME) values ('STARWORKS ENTERPRISE');
insert into MANUFACTURER (NAME) values ('FIRST PHILIPPINE SCALES, INC.');
insert into MANUFACTURER (NAME) values ('PHILIPPINE ADHESIVES INC.');

insert into PRODUCT_CATEGORY (NAME) values ('DAIRY PRODUCTS');
insert into PRODUCT_CATEGORY (NAME) values ('CANNED MEAT');
insert into PRODUCT_CATEGORY (NAME) values ('DETERGENTS AND FABRIC CONDITIONERS');
insert into PRODUCT_CATEGORY (NAME) values ('BREAKFAST ITEMS');
insert into PRODUCT_CATEGORY (NAME) values ('HOUSEHOLD PRODUCTS');

insert into SUPPLIER (NAME) values ('AMICI WATER SYSTEMS, PHILIPPINES');
insert into SUPPLIER (NAME) values ('ABENSON AVANT');
insert into SUPPLIER (NAME) values ('K SERVICO TRADE, INC.');
insert into SUPPLIER (NAME) values ('PHILGROCER');

insert into PRICING_SCHEME (NAME) values ('CANVASSER');