update PRODUCT set UNIT_CONV_CSE = 50000, UNIT_CONV_PCS = 1 where CODE = 'ALATAF100';
update PRODUCT set UNIT_CONV_CSE = 18, UNIT_CONV_PCS = 1 where CODE = 'AJIBLU5.2';
update PRODUCT set UNIT_CONV_CSE = 48, UNIT_CONV_CTN = 1 where CODE = 'BANAID100';
update PRODUCT set UNIT_CONV_CSE = 18, UNIT_CONV_DOZ = 1 where CODE = 'ARIPUL065';