update PRODUCT set UNIT_CONV_CSE = 50000, UNIT_CONV_PCS = 1 where CODE = 'ALATAF100';
update PRODUCT set UNIT_CONV_CSE = 18, UNIT_CONV_PCS = 1 where CODE = 'AJIBLU5.2';
update PRODUCT set UNIT_CONV_CSE = 48, UNIT_CONV_CTN = 1 where CODE = 'BANAID100';
update PRODUCT set UNIT_CONV_CSE = 18, UNIT_CONV_DOZ = 1 where CODE = 'ARIPUL065';

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID) values
((select ID from SUPPLIER where NAME = 'ABENSON AVANT'), (select ID from PRODUCT where CODE = '555CAL155'));

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID) values
((select ID from SUPPLIER where NAME = 'ABENSON AVANT'), (select ID from PRODUCT where CODE = '555HOT155'));

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID) values
((select ID from SUPPLIER where NAME = 'ABENSON AVANT'), (select ID from PRODUCT where CODE = '555MEC156'));

INSERT INTO SUPPLIER_PRODUCT (SUPPLIER_ID, PRODUCT_ID) values
((select ID from SUPPLIER where NAME = 'ABENSON AVANT'), (select ID from PRODUCT where CODE = '555OIL155'));

INSERT INTO PRODUCT_PRICE (PRICING_SCHEME_ID, PRODUCT_ID) select 2, ID from PRODUCT;