insert into USER (ID, USERNAME) values (1, 'PJ');

insert into MANUFACTURER (NAME) values ('PEDIAHEALTH CORPORATION');
insert into MANUFACTURER (NAME) values ('PHARMA EAST MEDICAL CORP.');
insert into MANUFACTURER (NAME) values ('QUANTUM RUBBER PRODUCTS CORP.');
insert into MANUFACTURER (NAME) values ('NUTRAHERB INC.');
insert into MANUFACTURER (NAME) values ('ALKAPURE WATER RESOURCES INC.');
insert into MANUFACTURER (NAME) values ('CROFS CONSTRUCTION AND DEVELOPMENT CO.');
insert into MANUFACTURER (NAME) values ('FIL-SCAN EXPORTS, INC.');
insert into MANUFACTURER (NAME) values ('STARWORKS ENTERPRISE');
insert into MANUFACTURER (NAME) values ('FIRST PHILIPPINE SCALES, INC.');
insert into MANUFACTURER (NAME) values ('PHILIPPINE ADHESIVES INC.');
