create table PRODUCT (
  ID INTEGER,
  CODE VARCHAR2(12),
  DESCRIPTION VARCHAR2(50),
  CONSTRAINT PRODUCT$PK PRIMARY KEY (ID),
  CONSTRAINT PRODUCT$CODE$UK UNIQUE (CODE)
);

insert into PRODUCT (ID, CODE, DESCRIPTION) values (1, 'CLORED010', 'CLOSE UP RED 10mlx288');
insert into PRODUCT (ID, CODE, DESCRIPTION) values (2, 'CLORED025', 'CLOSE UP RED 25mlx144');
insert into PRODUCT (ID, CODE, DESCRIPTION) values (3, 'CLORED050', 'CLOSE UP RED 50mlx72');
insert into PRODUCT (ID, CODE, DESCRIPTION) values (4, 'CLORED100', 'CLOSE UP RED 100mlx36');
insert into PRODUCT (ID, CODE, DESCRIPTION) values (5, 'CLORED150', 'CLOSE UP RED 150mlx24');