insert into SEQUENCE (NAME) values ('SALES_REQUISITION_NO_SEQ');
insert into SEQUENCE (NAME) values ('SALES_INVOICE_NO_SEQ');
insert into SEQUENCE (NAME) values ('STOCK_QTY_CONV_NO_SEQ');
insert into SEQUENCE (NAME) values ('PURCHASE_ORDER_NO_SEQ');
insert into SEQUENCE (NAME) values ('RECEIVING_RECEIPT_NO_SEQ');
insert into SEQUENCE (NAME) values ('ADJUSTMENT_OUT_NO_SEQ');
insert into SEQUENCE (NAME) values ('ADJUSTMENT_IN_NO_SEQ');
insert into SEQUENCE (NAME) values ('SUPPLIER_PAYMENT_NO_SEQ');
insert into SEQUENCE (NAME) values ('SUPP_PAYMENT_ADJUSTMENT_NO_SEQ');